const Constants = {
  submissionId: "submissionId",
  efileStatus: "efileStatus",
  userId: "userId",
  formId: "formId",
  created: "CREATED",
  rejected: "REJECTED",
  returnId: "returnId",
  apireturnid: "apireturnid",
  businessid: "businessid",
  sequence: "sequence",
  dbarefid: "dbarefid",
  recordstatus: "recordstatus",
  isupdatedreturn: "isupdatedreturn",
  formGroupId: "formGroupId",
  formGroupIdvalue: 4,
  apiReturnRecordId: "apiReturnRecordId",
  success: "SUCCESS",

  //API AddressBook URL
  GetBusinessDetailById: "/Business/GetBusinessDetailById",
  GetBusinessList: "/Business/GetBusinessList",
  GetBusinessIdByPayerRef: "/Business/GetBusinessIdByPayerRef",
  CheckIsValidBusiness: "/Business/CheckIsValidBusiness",
  DeleteBusinessDetailById: "/Business/DeleteBusinessDetailById",
  GetMainBusinessIdByUserId: "/Business/GetMainBusinessIdByUserId",
  UpdateDBADetails: "/Business/UpdateDBADetails",
  SaveBusinessDetail: "/Business/SaveBusinessDetail",
  GetBusinessIdListByUnformattedEinorSsn: "/Business/GetBusinessIdListByUnformattedTIN",
  UpdateBusinessDetail: "/Business/UpdateBusinessDetail",
  GetListBusinessIds: "/Business/GetListBusinessIds",
  ZipCodeList: "ZipCodeList",
  GetStateDetails: "getFormData?returnUniqueId=",
  GetQuarterDetails: "isQuarterEnabled?quarter=",
  GetReturnExistsDetails: "isReturnExist?quarter=",
}
export default Constants